server:
  port: 80

spring:
  application:
    name: sp
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3307/fruitable
    username: root
    password: r1r2r3
    hikari:
      connection-init-sql: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 4

logging:
  level:
    '[com.shop.fruitable.mapper]': TRACE
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl